### ISSUE TITLE
Definition of LOG macro

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/FairMQ#244]
**Is your feature request related to a problem? Please describe.**
`LOG` macro is defined when some of the FairMQ SDK headers are included. For instance, `<fairmq/sdk/Topology.h>`. The reason is that `<fairmq/sdk/Topology.h>` includes `<fairlogger/Logger.h>` which defines `LOG` macro. 

I think that defining a macro with such a common name `LOG` in the public header of FairMQ is a bad idea. For instance, in the ODC I use a custom `boost::log` based logger and also would like to define my own LOG macro.

**Describe the solution you'd like**
There are two options which came to my mind:
1. If possible do not `#include <fairlogger/Logger.h>` in the public headers but only in the cpp file. 
2. If you still need to log something in the header, define `LOG` macro with a different name, like `FAIRMQ_LOG` in order to prevent name clashes.

**Comment by dennisklein** [comment]
While I agree with your points and I would like to not use macros at all, we cannot easily get rid of the `LOG` macros in the <= C++17 versions of FairLogger, because it uses `__FILE__`, `__LINE__` and similar. (In the future we plan to switch to (`std::source_location`)[https://en.cppreference.com/w/cpp/utility/source_location])

Renaming is also not an option on the calling end - at least we do not know how to do it. We would have to rename it in the `<fairlogger/Logger.h>` header directly which will break every usage of it everywhere, which is also no option at the moment.

Because the `<fairmq/sdk/Topology.h>` contains open templates there is also no private cpp file to move the logging code to.

The above for explanation why we have to use macros at all.

---

To resolve this issue we propose to no longer include `<fairlogger/Logger.h>` in any of the sdk headers in one of the next commits which is not a perfect solution but should improve your situation at least.

**Comment by mattkretz** [comment]
Suggestion: In `Logger.h` rename the `LOG` macro to `FAIRMQ_LOG` (or whatever prefix you use consistently for macros) and use it instead of `LOG` throughout all *headers*. Add the following to `Logger.h`:
```c++
#ifdef FAIRMQ_DEFINE_LOG
#undef LOG
#define LOG FAIRMQ_LOG
#endif
```

Now in source files where you want to use the `LOG` macro, define `FAIRMQ_DEFINE_LOG` before including `Logger.h`:
```c++
#define FAIRMQ_DEFINE_LOG
#include <fairlogger/Logger.h>
```
Alternatively, turn the logic around and `#define LOG FAIRMQ_LOG` by default, unless `FAIRMQ_NO_LOG` is defined.

**Comment by rbx** [comment]
I sent a PR to FairLogger with the "alternative". Once its merged and tagged, we can bump FairLogger requirement here and use `FAIR_LOG` in our public headers.

**Comment by dennisklein** [comment]
@AndreyLebedev When using FairLogger v1.6.2+ and current FairMQ `dev` branch, the following

```cpp
#define FAIR_NO_LOG
#include<fairmq/SDK.h>
```

will result in the LOG macro to no longer be defined and is free for any other use. We believe this reolves the issue, please reopen otherwise.
