### ISSUE TITLE
fairmq-shmmonit zombies left behind once transport=shmem used

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#246]
**Describe the bug**
A bunch of `fairmq-shmmonit` zombies are left behind when a fairmq device topology using shmem as transport is quit. 

**To Reproduce**
not sure. Happens when in a container running a python script (i.e. the CI) a DPL workflow terminates correctly.

**Expected behavior**
Once the last device of the session quits, `fairmq-shmmonit` should quit.

**System information (please complete the following information):**
Linux

**Additional context**
Notice this behavior is new. In the past shmem was not always correctly working, but at least it was properly quitting when processing was done.

**Comment by ktf** [comment]
OK, just noticed that #216 is the same of this. Only difference is that now shared memory seems to work just fine.

**Comment by ktf** [comment]
Ok, maybe I understand. The problem is that docker does not reap deamons until the container exits.

**Comment by rbx** [comment]
Can you provide more details to help understand what is happening:
1. You mention multiple zombies. A single session should only launch a single shmmonitor. So I assume within the container you have multiple sessions? Unless it is another bug.
2. When the last device of a session quits, shmmonitor will stop receiving heartbeats within about 100ms and should exit by itself. There should be no crash. Would it be possible to see a coredump/backtrace from one of the crashed monitor processes?

**Comment by ktf** [comment]
multiple zombies are due to multiple tests happening.

the process terminates correctly, however since docker does not reap zombies until the container is gone no one waits for the daemonized process. is there a way to run the monitor myself from the dpl driver (e.g. in a separate child process) without detaching it?

**Comment by rbx** [comment]
Yes, you can disable the autolaunch of the monitor by passing `--shm-monitor false` to each device in the session.
The simplest way for you will be to just run it once after the session ends (perhaps also once before) with the cleanup call, it will do the right thing whether or not there is actually something to cleanup:
```
fairmq-shmmonitor --cleanup -s <sessionid>
```

**Comment by dennisklein** [comment]
Since Docker 1.13 there seems to be an option `--init` which injects a lightweight pid 1 process into the container that properly performs the duties of a pid 1 process such as reaping adopted orphans. Is this an option you can use?

**Comment by ktf** [comment]
Not sure. We use this via mesos / aurora, so I would need to check how to do it like that. In any case I am not sure what is the best strategy. Clearly we cannot enforce that on the grid or on private clusters.

**Comment by dennisklein** [comment]
As I understand posix requires any process that runs with PID 1 to implement "reaping", which is a `wait` on adopted orphan processes. Any child process that outlives its parent (intentional or not) is such an orphan that gets assigned parent pid 1.

I mean, we could teach all our processes (devices, and dpl executors) to implement reaping in case some broken container runtime runs no proper init process. Btw, bash implements reaping, so one could run the processes with `bash -c ...` in the container. (There was a comment that this still makes bash not a proper pid 1 for other reasons, but it may solve this issue.)

**Comment by dennisklein** [comment]
http://www.microhowto.info/howto/reap_zombie_processes_using_a_sigchld_handler.html - looks simple enough.

**Comment by ktf** [comment]
No, it's not that easy because we run with `--pid=host`, so the first process inside the container is not PID 1. Also you (fairmq) do `setsid()` in runMonitor which makes the SIGCHLD approach not working, AFAICT. The only solution would be to create a cgroup inside the DPL driver and have the driver itself do the reaping, but again that means you are actually allowed to create cgroups, which is not a given.

**Comment by ktf** [comment]
In principle we should be able to drop `--pid=host` now but I need to review what were the reasons for it.

**Comment by dennisklein** [comment]
Hm, but then I do not understand, why the `shmmon` are not reaped by the host pid 1? That would mean running without any containerization would also produce zombies, does it not?

**Comment by ktf** [comment]
Because it does not get attached to pid 1, but to dockerd.

**Comment by dennisklein** [comment]
Ah, I see, ok, then let us know, if dropping `--pid=host` (and adding `--init` or injecting some other from of reaping process into the tree) is an option that solves this for you.

I guess, we are also open to discuss adopting a different strategy than calling `setsid` in order to detach from the parent if you have any suggestions. The idea/goal is of course to have the `shmmon` process to live until the end of the fairmq session.

And as Alexey already wrote, a third option is to totally opting out of the auto-spawning of any `shmmon`s and clean the shm explicitely.

**Comment by ktf** [comment]
Yes, the third option is quite straightforward I already implemented it. Unfortunately @davidrohr has found some other issue with shared memory so we need to turn it off in any case, for now.
