### ISSUE TITLE
`fairmq-dds-command-ui -c c` always shows `UNDEFINED`

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#303]
We just found with @karabowi that the current implementation of the `-c c` command does not wait for the `fair::mq::sdk::Topology`'s internal state subscription to succeed and thus reports the `UNDEFINED` values which are set at initialization.

https://github.com/FairRootGroup/FairMQ/blob/690e8a037098ed4b7097f687d853d20a2b8cc028/fairmq/plugins/DDS/runDDSCommandUI.cxx#L61-L66

**Comment by dennisklein** [comment]
I would avoid to make `fair::mq::sdk::Topology::GetCurrentState()` blocking.

@rbx We could add a ctor argument `bool blockUntilConnected` which blocks the ctor until subscription acks have been received. Or as a separate member function `WaitUntilConnected()`. What do you think?

**Comment by rbx** [comment]
> I would avoid to make `fair::mq::sdk::Topology::GetCurrentState()` blocking.
Agreed, it returns only local state by design.
> @rbx We could add a ctor argument `bool blockUntilConnected` which blocks the ctor until subscription acks have been received. Or as a separate member function `WaitUntilConnected()`. What do you think?
I'm fine with both/any. 

But what you can already do now is:
https://github.com/FairRootGroup/FairMQ/blob/master/examples/dds/fairmq-start-ex-dds.sh.in#L55
Basically in the beginning wait until devices report to be IDLE.
That's why I wouldn't classify this issue as a bug.
