### ISSUE TITLE
Rework return codes of fairmq-dds-command-ui to return non-zero in error cases

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#316]

**Comment by ChristianTackeGSI** [comment]
Especially the "c" (check) command looks like it should have a proper exit code for error states?

**Comment by ChristianTackeGSI** [comment]
Another to consider:
```console
***** fairmq-dds-command-ui -c s
> stop devices
…
Device splitMC-gen cannot transition with STOP
```

**Comment by rbx** [comment]
> Another to consider:
> 
> ```
> ***** fairmq-dds-command-ui -c s
> > stop devices
> …
> Device splitMC-gen cannot transition with STOP
> ```

Which FairMQ tag produces the ` ... cannot transition with ... ` message?

**Comment by ChristianTackeGSI** [comment]
> Which FairMQ tag produces the `... cannot transition with ...` message?

Probably the old one from FairSoft:spack:jun19.
So I guess, you can ignore it.

I assume, Dennis and you know very well, which runtime paths should return an exit code != 0.

The main rule is: Give shell scripts an easy way to react to an error, if the error is severe enough.
If error scenarios are complex enough, you could even opt for different exit codes for different error classes. But I'd only go that route, if you can see clear ways of shell scripts having to react differently. Otherwise: Keep it simple.

**Comment by rbx** [comment]
So, I added the handling for the errors that SDK reports. See the linked PR.
 
> Especially the "c" (check) command looks like it should have a proper exit code for error states?

Thinking about this particular case, I'm not sure. This command requests states of all devices. If some of the devices are in the error state, is that a failure condition for the dds-ui-tool? Or is it's job simply to report the situation, and the consumer of this data should decide further. @dennisklein what do you think? I'm not strongly for or against it, but compared to other error conditions this one gives me a pause.

**Comment by ChristianTackeGSI** [comment]
A few thoughts about "c" check and exit codes:

If "the consumer" should be able to do decide, then you might consider to make the output "machine readable" and "stanle" (and declare that property officially). "stable" means, that there should not be any changes because of "better wording", or "formatting".

One obvious answer: If all (selected?) states are ERROR, then the exit code should indicate that.

For only some being in ERROR state: You're right, that case is not simple. I don't have a simple answer there.

**Comment by rbx** [comment]
Thinking about it more, it's better to return non-zero even if any of the devices are in error. The consumer just has to take that case into account. Updated the PR.
